import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import Navbar from './Components/Navbar'
import Footer from './Components/Footer'
import Layout from './Components/Layout'
import React, { useState } from 'react';



export default function Home() {

    const [color, setColor] = useState("grey");
    const [currIndex, setCurrentIndex] = useState(0);

    const handleReview = () => {
      setColor("yellow");
    };

    const handleDump = () => {
      setColor("white");
    };


    const handleNext = () => {
      if (currIndex > 9){
        setCurrentIndex(10);
      }else{
        setCurrentIndex(currIndex+1);
      }      
      setColor("green");
    };

    const handlePrevious = () =>{
      if (currIndex <= 1){
        setCurrentIndex(1);
      }else{
        setCurrentIndex(currIndex-1);
      }
    }

    const handleClearResponse = () => {
      setColor("grey");
    };
  return (
    <>
      <Head>
        <title>Exam Panel</title>
        <meta name="Exam Panel made using next js" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossOrigin="anonymous" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <div style={{backgroundColor: '#6699CC'}}>
        <h2 style={{textAlign: "center"}} className="text-light"><strong>DEMO ONLINE TEST</strong></h2>
      </div>
      <Navbar></Navbar>
      <Layout name= "Kumar Shivam" color={color} index={currIndex}></Layout>
      <div className='buttons my-2' style={{marginLeft: '15px'}}>
                <button type="button" className="btn btn-primary me-5" onClick={() => handleClearResponse()}>CLEAR RESPONSE</button>
                <button type="button" className="btn btn-primary me-5" onClick={() => handleReview()}>REVIEW</button>
                <button type="button" className="btn btn-primary me-5" onClick={() => handleDump()}>DUMP</button>
                <button type="button" className="btn btn-primary me-5" onClick={() => handlePrevious()}>PREVIOUS</button>
                <button type="button" className="btn btn-primary me-5" onClick={() => handleNext()}>NEXT</button>
      </div>      
      <Footer></Footer>    
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossOrigin="anonymous"></script>
    </>
  )
}
